### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by schancel** [cashaddress/cashaddress.github.io#1]
Thanks for setting this up.  It might be good to have this github org be a nexus for implementations in various languages.

**Comment by DesWurstes** [comment]
I'm also working on a native JS implementation.

**Comment by schancel** [comment]
Would you mind joining the wallet developer discussion group?  There's a couple people asking about a JS CashAddress implementation.

https://github.com/schancel/bitcoin-cash-workgroups/blob/master/wg-wallets/workgroup.md
