### ISSUE TITLE
Copy address to clipboard on click

### ISSUE THREAD

**Issue by cashaddressio** [cashaddress/cashaddress.github.io#3]
I think it would be great if you could add a copy to clipboard function when the qr or address gets clicked.

Great work so far.  Keep it up!

---
Owner of cashaddress.io

cashaddressio@tutanota.com

**Comment by DesWurstes** [comment]
Hi, in case if you're planning to create a fork of this website, I encourage you to wait 1-2 days, I'll mention you when I clean up the source code.

Sure, will add that feature soon.

**Comment by DesWurstes** [comment]
OK, now there's a copy button, and I've cleaned the code up. Feel free to fork the code.
